{% set name = "pylogit" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylogit-{{ version }}.tar.gz
  sha256: 191ffc50b8a103dc6a36ef61dfbe5e7c2d6c24e439f821284b1271706f879fc5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2,<4
  run:
    - python >={{ python_min }}
    - future >=0.16
    - numpy >=1.10.2
    - pandas >=0.16.2
    - scipy >=0.16.1
    - statsmodels >=0.6.1
    - tqdm >=4.15.0

test:
  imports:
    - pylogit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/timothyb0912/pylogit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python package for estimating conditional logit models

extra:
  recipe-maintainers:
    - gboeing
