{% set name = "pylogit" %}
{% set version = "1.0.0" %}
{% set sha256 = "b12c6658fcd364e4eb21cd91a80957a374dbf4bb559e76aadfcec5554a03c109" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - future >=0.16
    - numpy >=1.10.2
    - pandas >=0.16.2
    - scipy >=0.16.1
    - statsmodels >=0.6.1
    - tqdm >=4.15.0

test:
  imports:
    - pylogit

about:
  home: https://github.com/timothyb0912/pylogit
  license: BSD-3-Clause
  license_family: BSD
  # license file to be added to distribution in https://github.com/timothyb0912/pylogit/pull/18
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A Python package for estimating conditional logit models

extra:
  recipe-maintainers:
    - gboeing
