travis:
  secure:
    BINSTAR_TOKEN: S134P24uBvt281mH5RlmacbE29bUnahKV1Ogxk9PceAPlLbWg6rulezwQL5IjuPuacQciSpyMkJCqxzWRmIKbpv5+ezl7RlkdQyO2lx0XW19ieeE0NSmn8h8vrGyQeTQF0HRQfmLqO7YCm6+Nzz6pSMhfdSa2hctjOSbnJdYL8NzYkYbAzqFlpVbFj8ssMlZhMKqveUCQzd4tDjPVR3axdBQWzHytW08wslKW2zF4r4V4+TIA6mK7j4yWqgzp0ADORwtVVuyJjJzQK0zyV8qOHlk/dCHRDpO3u4YuNbsYhA41wVi0vz8OU+/WoAQL3QuDxWY0sFxG9HPCa8ZqAQjgIL3fDTSk5NpfWQIHQQHn5a7tSV4J1q4t3/SxGPv1GZX+KsErQpKwVkg9Gd3IgmgJzMfBwawUOlIgllgnFVY2aBKSeWB5iFoZrOLyIMxA4VIhRbzQqxQO9Oz7iVLed5+q0K60dtadEPpZLeqfpTlMrn7ajQA4URimOP8x217XswXAc2Z3XB409g0GbTzG8+xqYEmuTrjCUg0IJHwisFTayUuIaR+r+7BigjhCY9Q0cjWe1cUjagGN+Toe55Rlk+ggaUsJQj+/g9lYJbYE/OUah8y22zqM2X1POO79fQTZzhDsnH1iQ4sp1cQ989MJvtnuqdVTx0tfuRPjr0lkzEc4O0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
