travis:
  secure:
    BINSTAR_TOKEN: HKo/NLXfQyR+FmIW+0gBXiUoU2VIvfYtnwLn5rTc27ZakddjQm0V0AuWbCJLkfrZz8E11PpfM/52Lirw2J0AJdc8XpUDO7gCyZvVdfAvjOYruuuc5tgxnhFWKkgeit86uchvmxrGOmItk2Nk1QBMgvK2+obPahUrgUdsCANSiOBLb84uN2rLpH8tVrdbHmkmerrikhnaTN4i8wDUcIGh/MSIhf4afE47zT+U7ArBG3J6g7+LRWDH8kZm7ZCbtjejnPrvobXSgCti7JkwkanFp/M86KjZowpH/46ZrOJ0C9Pls/dSBCPIsE7FAIQv7k1ny6VAkni4CRvoA7TKobXk/K09OY3j96RnMw67YVnRIu9U0L8pKobWHgSsI1UeKygSjaAVMFEuSkOkeewLBwjQHeZuQLJuCEQTLD8GxaVf0TD/S6TqHW0ytk+R94EUkF4o4KenvwVt4eyX/6dPZsGT8t0XS0C0aYnaxLX2R+ehh0keNXbJpKtfFSl66b4cJLiC6t2HnXHqNGl0LrygC/oSaq1z4aWW0xACCTC74DKMep06MNsYxnpoMWmFAhKkZXlMAd/4g3oroi5VLIePwrcLJaCBIhq74vaO2u8W13BuQEOR4KUhKlcEFYmGLahwO5Ok3dTXVLrqZV9zm1fnSGer9F83/WGyL97r02Yed4CWLbE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
